- recipe/meta.yaml
- recipe/run_test.py
Also remove ``stats.vonmises_cython`` as import in run_test.py, because
that extension module has been removed in scipy master and therefore
that import will give an issue with scipy 0.18.0 soon.
> MAINT: add mpmath as test dependency, add self as maintainer.

- recipe/build.sh
- recipe/meta.yaml
This is an attempt to make sure `clang++` and `libc++` are used to build SciPy. As there are some C++ STL types being exposed and the rest of our stack using `clang++` and `libc++`, it is very important for SciPy to be compliant. However, this may be tricky given the requirement to have `gfortran`. Let's see what we can do.
> Try to use `clang++`

- .travis.yml
Not sure if we are going to need this or not. In some cases we have had bad symlinks getting packaged when using activation scripts (like those in the `toolchain`) like as shown in this issue ( https://github.com/conda-forge/hdf5-feedstock/issues/23 ). Though we haven't seen this problem crop up recently and are not totally sure why. There may have been a change in `conda` that has made this unnecessary, but we have been unable to confirm. So, am just readying this in case it is needed.
xref: https://github.com/conda-forge/scipy-feedstock/pull/2
cc @pelson @rgommers @gillins
> Unpin conda-build on Travis CI [ci skip]

- ci_support/run_docker_build.sh
- recipe/meta.yaml
- recipe/yum_requirements.txt
Currently, we are shipping the whole `libgcc` package on Linux with `scipy`. This has proved problematic in our stack especially as was seen with `numpy` ( https://github.com/conda-forge/numpy-feedstock/issues/15 ). However, unlike with `openblas` we cannot simply just ship `libgfortran` as `scipy` has C++ code and thus depends on `libstdc++`. Given the shipping of `libstdc++` was the cause of the issues with code depending on `numpy`, it is tricky to find an easy fix here.
There are two main options to avoid shipping `libstdc++`. First, try to use `gfortran` and `libgfortran` from the `gcc` package only and otherwise use the image compilers and libraries. Second, try to use system compilers for the whole process, but have everything link to our `libgfortran` instead. Attempts to get the …
> Only ship libgfortran

- .travis.yml
- README.md
- ci_support/run_docker_build.sh
- recipe/meta.yaml
As it seems to be too much to build 2 NumPy versions and 3 Python versions on CircleCI, I'm proposing we break them up into 2 branches that build with 1 NumPy each. This should be well within the time limit. Think of this as a poor man's build matrix. In the long run, we will want to have some sort of build matrix support via CircleCI's parallelism feature as explained in issue ( https://github.com/conda-forge/conda-smithy/issues/203 ). However, after spending some time on it, it is clear to me this is going to take a bit more work. Unfortunately, I don't have the time to dedicate to that problem at present. So, I'm punting on it by breaking these up in the hopes of solving downstream package build issues seen in PRs ( https://github.com/conda-forge/pytmatrix-feedstock/pull/4 ) and ( …
> Config SciPy v0.17 build with NumPy 1.11

- .travis.yml
- README.md
- ci_support/run_docker_build.sh
- recipe/meta.yaml
As it seems to be too much to build 2 NumPy versions and 3 Python versions on CircleCI, I'm proposing we break them up into 2 branches that build with 1 NumPy each. This should be well within the time limit. Think of this as a poor man's build matrix. In the long run, we will want to have some sort of build matrix support via CircleCI's parallelism feature as explained in issue ( https://github.com/conda-forge/conda-smithy/issues/203 ). However, after spending some time on it, it is clear to me this is going to take a bit more work. Unfortunately, I don't have the time to dedicate to that problem at present. So, I'm punting on it by breaking these up in the hopes of solving downstream package build issues seen in PRs ( https://github.com/conda-forge/pytmatrix-feedstock/pull/4 ) and ( …
> Config SciPy v0.17 build with NumPy 1.10

- .travis.yml
- README.md
- ci_support/run_docker_build.sh
- recipe/build.sh
- recipe/meta.yaml
This extends the same strategy used with SciPy v0.17 to v0.18 as was proposed for the NumPy 1.11 build in PR ( https://github.com/conda-forge/scipy-feedstock/pull/10 ). Also absorbs PR ( https://github.com/conda-forge/scipy-feedstock/pull/12 ) while we are at it. The NumPy 1.10 build is in PR ( https://github.com/conda-forge/scipy-feedstock/pull/16 ).
Additionally I propose that `master` stays up-to-date with this branch. There are many cases where a `master` branch is required. As a result, it is merely a matter of choosing where it is. Having it follow the latest version of SciPy with the latest version of NumPy makes a lot of sense.
> Config SciPy v0.18 build with NumPy 1.11

- .travis.yml
- README.md
- ci_support/run_docker_build.sh
- recipe/build.sh
- recipe/meta.yaml
This extends the same strategy used in with SciPy v0.17 to v0.18 as was proposed for the NumPy 1.10 build in PR ( https://github.com/conda-forge/scipy-feedstock/pull/11 ). Also absorbs PR ( https://github.com/conda-forge/scipy-feedstock/pull/12 ) while we are at it. The NumPy 1.11 build is in PR ( https://github.com/conda-forge/scipy-feedstock/pull/17 ).
> Config SciPy v0.18 build with NumPy 1.10

- recipe/meta.yaml
```
==========================
SciPy 0.19.1 Release Notes
==========================
SciPy 0.19.1 is a bug-fix release with no new features compared to 0.19.0.
The most important change is a fix for a severe memory leak in
``integrate.quad``.
Authors
=======
* Evgeni Burovski
* Patrick Callier +
* Yu Feng
* Ralf Gommers
* Ilhan Polat
* Eric Quintero
* Scott Sievert
* Pauli Virtanen
* Warren Weckesser
A total of 9 people contributed to this release.
People with a "+" by their names contributed a patch for the first time.
This list of names is automatically generated, and may not be fully complete.
Issues closed for 0.19.1
------------------------
- `#7214 <https://github.com/scipy/scipy/issues/7214>`__: Memory use in integrate.quad in scipy-0.19.0
- `#7258 …
```
> Update to 0.19.1

- .travis.yml
- ci_support/run_docker_build.sh
Adding Python 3.4 version of `scipy` for academic reasons. This can be removed in the next re-render.
> force add py34

- recipe/meta.yaml
abi-laboratory reports are misleading because they don't have lapack symbols listed.
> Pin openblas exactly

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.7.____73_pypy.yaml
- .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.7.____73_pypy.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.7.____73_pypy.yaml
- .ci_support/migrations/pypy37.yaml
- .ci_support/osx_64_numpy1.19python3.7.____73_pypy.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .drone.yml
- .github/CODEOWNERS
- .travis.yml
- README.md
There's some weird cycles in the dependency graph that make the migrator think that scipy depends on pandas and psycopg2, among others, see https://github.com/regro/cf-scripts/issues/1331
I verified that all dependencies have been built (hopefully not overlooking anything), so raising this to break some of these cycles.
> Manual pypy37 migration

- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
This has become obvious because the CI for #151 passed. Incidentally, also helpful because one of the aarch-builds timed out on master.
> remove redundant version guard

- recipe/meta.yaml
Trying to get aarch to stop timing out again.
> reduce test modules on aarch again

- recipe/bld.bat
- recipe/meta.yaml
- recipe/patches/0001-BUG-Fix-importing-scipy.lib._pep440.patch
- recipe/patches/0002-parametrize-test_ldl_type_size_combinations.patch
Had been disabled to unblock release of 1.8.0
Closes #196
> re-enable pythran on windows; test skip hyghiene

- recipe/meta.yaml
Hopefully less flaky than after #204
> skip longest running tests for pypy on aarch

- recipe/meta.yaml
Spurred by the success of https://github.com/conda-forge/numpy-feedstock/pull/274, let's try for scipy as well
> re-enable testing for PPC in emulation

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_numpy1.20python3.8.____73_pypypython_implpypy.yaml
- .ci_support/linux_64_numpy1.20python3.9.____73_pypypython_implpypy.yaml
- .ci_support/linux_aarch64_numpy1.20python3.8.____73_pypypython_implpypy.yaml
- .ci_support/linux_aarch64_numpy1.20python3.9.____73_pypypython_implpypy.yaml
- .ci_support/linux_ppc64le_numpy1.20python3.8.____73_pypypython_implpypy.yaml
- .ci_support/linux_ppc64le_numpy1.20python3.9.____73_pypypython_implpypy.yaml
- .ci_support/osx_64_numpy1.20python3.8.____73_pypypython_implpypy.yaml
- .ci_support/osx_64_numpy1.20python3.9.____73_pypypython_implpypy.yaml
- .ci_support/win_64_numpy1.20python3.8.____73_pypypython_implpypy.yaml
- .ci_support/win_64_numpy1.20python3.9.____73_pypypython_implpypy.yaml
- README.md
- recipe/meta.yaml
Taken out from #206 because the builds came in late during the rc-phase and aren't yet fully fixed.
> Re-enable pypy

- recipe/build.sh
Unexpected breakage in #200 (after #231 passed a few days ago). Investigating
> Fix CI with stricter meson-python

- recipe/meta.yaml
- recipe/patches/0001-BLD-use-a-relative-path-to-numpy-pybind11-pythran-in.patch
- recipe/patches/0002-BLD-avoid-running-run_command-py3-.-for-better-cross.patch
- recipe/patches/0003-BUG-some-tweaks-to-PROPACK-f2py-wrapper-and-build-fl.patch
- recipe/patches/0004-MAINT-remove-from-numpy.math-cimport-usages.patch
- recipe/patches/0005-MAINT-sync-changes-to-npy_blas.h-and-npy_blas_base.h.patch
- recipe/patches/0006-BUG-include-npy_common.h-in-npy_cblas.h.patch
- recipe/patches/0007-BLD-fix-two-regressions-for-Duse-g77-abi.patch
As discovered in https://github.com/conda-forge/scipy-feedstock/pull/224, support for netlib was broken by the switch to meson, backport the fixes, confirmed to work also in that PR.
CC @rgommers
> backport 3 PRs for CBLAS compat

- recipe/bld.bat
- recipe/meta.yaml
- recipe/patches/0001-BLD-use-a-relative-path-to-numpy-pybind11-pythran-in.patch
- recipe/patches/0002-BLD-avoid-running-run_command-py3-.-for-better-cross.patch
- recipe/patches/0003-BUG-some-tweaks-to-PROPACK-f2py-wrapper-and-build-fl.patch
- recipe/patches/0004-MAINT-remove-from-numpy.math-cimport-usages.patch
- recipe/patches/0005-MAINT-sync-changes-to-npy_blas.h-and-npy_blas_base.h.patch
- recipe/patches/0006-BUG-include-npy_common.h-in-npy_cblas.h.patch
- recipe/patches/0007-BLD-fix-two-regressions-for-Duse-g77-abi.patch
- recipe/patches/0008-BLD-add-numpy-and-python-include-dirs-to-propack-sta.patch
- recipe/patches/0009-BLD-fix-yet-another-PROPACK-build-issue.patch
Excluded from #233 to make forward progress, I realised we should ensure these patches work on windows, so that 1.11 remains buildable with distutils.
> also enable recent patches on windows

- recipe/meta.yaml
A quick release to fix a licensing [issue](https://github.com/scipy/scipy/issues/18765) (scipy actually yanked 1.11.0; not sure if we want to mark the builds as broken)
> SciPy 1.11.1

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_numpy1.26python3.12.____cpythonpython_implcpython.yaml
- .ci_support/linux_aarch64_numpy1.26python3.12.____cpythonpython_implcpython.yaml
- .ci_support/linux_ppc64le_numpy1.26python3.12.____cpythonpython_implcpython.yaml
- .ci_support/migrations/python312.yaml
- .ci_support/osx_64_numpy1.26python3.12.____cpythonpython_implcpython.yaml
- .ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml
- .ci_support/win_64_numpy1.22python3.10.____cpythonpython_implcpython.yaml
- .ci_support/win_64_numpy1.22python3.9.____73_pypypython_implpypy.yaml
- .ci_support/win_64_numpy1.22python3.9.____cpythonpython_implcpython.yaml
- .ci_support/win_64_numpy1.23python3.11.____cpythonpython_implcpython.yaml
- .ci_support/win_64_numpy1.26python3.12.____cpythonpython_implcpython.yaml
- README.md
- recipe/bld.bat
- recipe/build-output.bat
- recipe/build-output.sh
- recipe/build.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
This is a cleaned-up version of #246, taking into account learnings & patches contributed by several people (also in #252 & #253), some of which were directly upstreamed to scipy and made it into 1.11.3 already.
Requires builds from https://github.com/conda-forge/flang-feedstock/pull/28 & ~https://github.com/conda-forge/meson-feedstock/pull/89~ https://github.com/conda-forge/meson-feedstock/pull/92 which are currently only available under `llvm_rc` and `meson_dev` labels. This will hopefully improve soon.
It's likely that this will still need some work around compiler-activation, flags, etc.; but with a passing test suite in #246, we should be good for more in-depth review.
Closes #253
Closes #252 
Closes #246 
Closes #213
Closes #164
> meson on windows with clang-cl & flang; python 3.12 support

- recipe/meta.yaml
- recipe/patches/0001-TST-Add-RNG-seeds-for-TestInvgauss-and-TestLaplace-1.patch
- recipe/patches/0002-BLD-fix-issue-with-escape-sequences-in-__config__.py.patch
Fixes #264
And while we're at it, backport a PR for the spurious test failures on that crop up on PPC.
> backport patch for spurious warning on windows

- recipe/meta.yaml
- recipe/patches/0001-MAINT-fix-typo-in-small_dynamic_array.h-21069.patch
A small fix for an unintentional change introduced by https://github.com/conda-forge/scipy-feedstock/commit/3b582be8b3642857c5d67335d49fe2ee3184c280; plus pick up a fix we'll need for #269
> ignore libflang run-export for scipy-tests
