conda-forge/scipy-feedstock

recipe/build.sh
recipe/meta.yaml
recipe/run_test.py

Bump build number and rebuild with the parallel OpenBLAS.
cc @ocefpaf

Rebuild with parallel OpenBLAS

---

recipe/meta.yaml

update scipy to 0.18.1

---

recipe/meta.yaml

update to scipy 0.18.1

---

recipe/meta.yaml

Now that my test in #44 worked we can remove the skip.

Remove the numpy skip

---

ci_support/run_docker_build.sh
recipe/meta.yaml

Build only np111 for Linux on this branch

---

ci_support/run_docker_build.sh
recipe/meta.yaml

See https://github.com/conda-forge/scipy-feedstock/pull/47

Build only np112 for Linux on master

---

.travis.yml
LICENSE
ci_support/fast_finish_ci_pr_build.sh
ci_support/run_docker_build.sh
circle.yml
recipe/meta.yaml

See https://github.com/scipy/scipy/releases/tag/v0.19.0

Update to 0.19.0

---

.travis.yml
LICENSE
ci_support/fast_finish_ci_pr_build.sh
ci_support/run_docker_build.sh
circle.yml
recipe/meta.yaml

Update to 0.19.0 np111

---

recipe/build.sh

Backported from PR ( https://github.com/conda-forge/scipy-feedstock/pull/62 ) for the NumPy 1.11 branch.
cc @isuruf

Remove openblas hacks (NumPy 1.11)

---

.travis.yml
recipe/meta.yaml

Fix NumPy 1.11 selector [skip ci]

---

.travis.yml
recipe/meta.yaml

Fix NumPy 1.12 selector [skip ci]

---

.travis.yml
recipe/meta.yaml

Fix NumPy 1.13 selector [skip ci]

---

recipe/meta.yaml

Need by https://github.com/conda-forge/scikit-learn-feedstock/pull/57

update numpy pinning

---

.ci_support/linux_python2.7.yaml
.ci_support/linux_python3.5.yaml
.ci_support/linux_python3.7.yaml
.ci_support/osx_python2.7.yaml
.ci_support/osx_python3.5.yaml
.ci_support/osx_python3.6.yaml
.ci_support/osx_python3.7.yaml
.circleci/config.yml
.github/PULL_REQUEST_TEMPLATE.md
recipe/meta.yaml

testing py37

---

.ci_support/linux_python3.6.yaml
.ci_support/linux_python3.7.yaml
.ci_support/osx_python3.6.yaml
.ci_support/osx_python3.7.yaml
recipe/meta.yaml

remove numpy constraint

---

recipe/build.sh
recipe/gh10591.patch
recipe/meta.yaml

Use scipy/scipy#10591

---

.ci_support/linux_ppc64le_numpy1.18python3.6.____73_pypypython_implpypy.yaml
.travis.yml
README.md
recipe/meta.yaml
recipe/run_test.py

Checklist
Fixes https://github.com/conda-forge/scipy-feedstock/issues/125

enable pypy on ppc64le

---

.azure-pipelines/azure-pipelines-win.yml
recipe/meta.yaml

Checklist
Rebased #142 after #146 
Closes #142.
Drone is expected to time out again, but that's the current state on master anyway, and can be fixed independently IMO.

v1.5.3 (redux)

---

recipe/meta.yaml

[ci skip] fewer teams for me

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_numpy1.17python3.7.____cpythonpython_implcpython.yaml
.ci_support/linux_64_numpy1.17python3.8.____cpythonpython_implcpython.yaml
.ci_support/linux_64_numpy1.19python3.7.____73_pypypython_implpypy.yaml
.ci_support/linux_64_numpy1.19python3.9.____cpythonpython_implcpython.yaml
.ci_support/linux_aarch64_numpy1.17python3.7.____cpythonpython_implcpython.yaml
.ci_support/linux_aarch64_numpy1.17python3.8.____cpythonpython_implcpython.yaml
.ci_support/linux_aarch64_numpy1.19python3.7.____73_pypypython_implpypy.yaml
.ci_support/linux_aarch64_numpy1.19python3.9.____cpythonpython_implcpython.yaml
.ci_support/linux_ppc64le_numpy1.17python3.7.____cpythonpython_implcpython.yaml
.ci_support/linux_ppc64le_numpy1.17python3.8.____cpythonpython_implcpython.yaml
.ci_support/linux_ppc64le_numpy1.19python3.7.____73_pypypython_implpypy.yaml
.ci_support/linux_ppc64le_numpy1.19python3.9.____cpythonpython_implcpython.yaml
.ci_support/osx_64_numpy1.17python3.7.____cpythonpython_implcpython.yaml
.ci_support/osx_64_numpy1.17python3.8.____cpythonpython_implcpython.yaml
.ci_support/osx_64_numpy1.19python3.7.____73_pypypython_implpypy.yaml
.ci_support/osx_64_numpy1.19python3.9.____cpythonpython_implcpython.yaml
.ci_support/osx_arm64_python3.8.____cpython.yaml
.ci_support/osx_arm64_python3.9.____cpython.yaml
.ci_support/win_64_numpy1.17python3.7.____cpython.yaml
.ci_support/win_64_numpy1.17python3.8.____cpython.yaml
.ci_support/win_64_numpy1.19python3.9.____cpython.yaml
.drone.yml
.travis.yml
README.md
recipe/bld.bat
recipe/build.sh
recipe/meta.yaml
recipe/patches/sobol_stack_smash.patch

Checklist
fixes #173. Reported upstream as scipy/scipy#14363

test patch for sobol stack smashing

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_numpy1.18python3.7.____cpythonpython_implcpython.yaml
.ci_support/linux_64_numpy1.18python3.8.____cpythonpython_implcpython.yaml
.ci_support/linux_64_numpy1.19python3.7.____73_pypypython_implpypy.yaml
.ci_support/linux_64_numpy1.19python3.9.____cpythonpython_implcpython.yaml
.ci_support/linux_aarch64_numpy1.18python3.7.____cpythonpython_implcpython.yaml
.ci_support/linux_aarch64_numpy1.18python3.8.____cpythonpython_implcpython.yaml
.ci_support/linux_aarch64_numpy1.19python3.7.____73_pypypython_implpypy.yaml
.ci_support/linux_aarch64_numpy1.19python3.9.____cpythonpython_implcpython.yaml
.ci_support/linux_ppc64le_numpy1.18python3.7.____cpythonpython_implcpython.yaml
.ci_support/linux_ppc64le_numpy1.18python3.8.____cpythonpython_implcpython.yaml
.ci_support/linux_ppc64le_numpy1.19python3.7.____73_pypypython_implpypy.yaml
.ci_support/linux_ppc64le_numpy1.19python3.9.____cpythonpython_implcpython.yaml
.ci_support/osx_64_numpy1.18python3.7.____cpythonpython_implcpython.yaml
.ci_support/osx_64_numpy1.18python3.8.____cpythonpython_implcpython.yaml
.ci_support/osx_64_numpy1.19python3.7.____73_pypypython_implpypy.yaml
.ci_support/osx_64_numpy1.19python3.9.____cpythonpython_implcpython.yaml
.ci_support/win_64_numpy1.18python3.7.____cpythonpython_implcpython.yaml
.ci_support/win_64_numpy1.18python3.8.____cpythonpython_implcpython.yaml
.ci_support/win_64_numpy1.19python3.7.____73_pypypython_implpypy.yaml
.ci_support/win_64_numpy1.19python3.9.____cpythonpython_implcpython.yaml
.gitattributes
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
build-locally.py
conda-forge.yml
recipe/meta.yaml

Cross compile instead of emulating

---

recipe/meta.yaml
recipe/patches/0001-add-break_cycles-for-mmapped-file-in-test_netcdf.patch
recipe/patches/0002-parametrize-test_wavfile.test_write_roundtrip.patch
recipe/patches/0003-add-break_cycles-for-mmapped-file-in-test_wavfile.patch
recipe/patches/0004-TST-remove-fragile-test-which-checks-if-g77-is-linke.patch

For some reason the bot errored, but the status page says:
``` 
No error information available for version '1.7.3'.
```
In any case, let's build it!

Scipy 1.7.3

---

.azure-pipelines/azure-pipelines-win.yml
.circleci/config.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml

[main] numpy upper bound

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_aarch64_numpy1.20python3.8.____73_pypypython_implpypy.yaml
.ci_support/linux_aarch64_numpy1.20python3.9.____73_pypypython_implpypy.yaml
.ci_support/linux_ppc64le_numpy1.20python3.8.____73_pypypython_implpypy.yaml
.ci_support/linux_ppc64le_numpy1.20python3.9.____73_pypypython_implpypy.yaml
README.md
recipe/meta.yaml

Testing how far we can reduce old test skips these days

remove old test skips

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-win.yml
.scripts/run_osx_build.sh
recipe/build-output.bat
recipe/meta.yaml

SciPy 1.11.2
